### ISSUE TITLE
You never mentioned that this package does almost nothing, frankly speaking...

### ISSUE THREAD

**Issue by zhekaus** [jadjoubran/laravel-angular#11]
...and, actually, doesn’t do anything with Angular. And hence its name, that’s quite weird.
All you suggest here is an opinioned simple template of api call responses.
However, Angular can consume Laravel API right out of the box.
I don’t understand why people star it at all.

**Comment by jadjoubran** [comment]
Hi @zhekaus 
Thanks for opening an issue!
This repository is for the Laravel package
The Angular package was supposed to go in [angular-laravel](https://github.com/jadjoubran/angular-laravel)

However I never had the time to work on it due to time constraints
If you can send in a contribution, I'd be happy to work with you on it! 😄 

Indeed Angular can consume Laravel API right out of the box, it's nowhere claimed the opposite. However this package helps you return consistent responses for errors and success based on the response macro described in the documentation.
I'm waiting for the package to evolve with feedback from the community, so if you've got any feature suggestion, feel free to create one!
Cheers

**Comment by zhekaus** [comment]
The only reason to have such a thingy as laravel-angular is having working-out-of-the-box demo with 
self-sufficient tutorial. 
That what people really need. That what is still absent for tymondesigns/jwt-auth *version 1.0*

I saw your laravel-angular.io, indeed. And it is far from being completed. Currently it simply contains copy-pasts from origins. However, thanks so much, it gives the idea and it is a good start: for you – to create something really useful, for others, currently – to follow the origins and comprehend them there.

Nonetheless, I don’t see any use in any kind of laravel-angular package though.

**Comment by jadjoubran** [comment]
I'm going to have time to work on it again very soon, so I've you come up with new specific features that you think are nice to have, please open a new issue on either one of the repositories
Cheers!

**Comment by lakinmohapatra** [comment]
It will be good to have one user interface for developing apis like
loopback node js framework .
