### ISSUE TITLE
is it Angular 4 the last version ?

### ISSUE THREAD

**Issue by c1t1zen** [jadjoubran/laravel-angular#6]
Hey!
I wonder if you use the last version of Angular 4. 
Also i ask if we can use angular 4 with laravel 5.5

Thank you in advance

**Comment by jadjoubran** [comment]
Hi @c1t1zen 
With this package, you have the freedom to use whichever Angular version you'd like. So yes you can use the Angular-cli (as mentioned in the documentation) in order to scaffold your new Angular (4) app.
Laravel 5.5 should work, but right now it's tested with 5.4

**Comment by c1t1zen** [comment]
Hi @jadjoubran 
thank you for reply
the documentation only talk about AngularJs no mention how to use Angular 4 with
and where can i install or setup Angular app in laravel project root?

**Comment by jadjoubran** [comment]
Hi @c1t1zen 
Sorry I should've mentioned, the new documentation is solely on https://laravel-angular.io/ (rather than on the old website readme.io)
It's not recommended to setup the Angular app in the laravel project root as you'll end up with way too many files and it becomes unmanageable.. I'd recommend you use the Angular CLI in a different project
I'll be working on a screencast soon!

**Comment by c1t1zen** [comment]
Thank you @jadjoubran
